name: Stage
on:
  push:
    branches: ["workflows"]

jobs:
  ssh-into:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Copying files to the destination
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        LIVE_USER: ubuntu
        HOST: 52.205.227.18
        PORT: 22
        DEST: /home/ubuntu/deployment
      run: |
        echo -e "${SSH_KEY}" > keyfile
        chmod 600 keyfile
        ssh -p $PORT -i keyfile $LIVE_USER@$HOST "cd /home/pmuser/delete-files-test && rm -rf testfile1.txt "