name: Stage
on:
  push:
    branches: ["workflows"]

jobs:
  ssh-into:
    runs-on: ubuntu-latest

    steps:
    
      - name: deploy to server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-e -c -r --delete"
          SERVER_PORT: ${{ secrets.PORT }}
          FOLDER: "/home/pm-suman/cicdforwp/wordpress/wp-content/*"
          SERVER_IP: 34.239.246.114
          USERNAME: ${{ secrets.LIVE_USER }}
          SERVER_DESTINATION: ${{ secrets.DEST }}