name: Stage
on:
  push:
    branches: ["workflows"]
  workflow_dispatch:

jobs:
  ssh-into:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Copying files to the destination
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        LIVE_USER: ubuntu
        HOST: 52.205.227.18
        PORT: 22
        command_timeout: 100
        DEST: /home/ubuntu/deployment
      run: |
        echo -e "${SSH_KEY}" > keyfile
        chmod 600 keyfile
        echo "rsync live"
        rsync -r --timeout=300 -e "ssh -i keyfile -o StrictHostKeyChecking=no" wordpress/wp-content/themes/ ubuntu@52.205.227.18:/home/ubuntu/wp/disk/wordpress/wp-content/themes/
        rsync -r --timeout=300 -e "ssh -i keyfile -o StrictHostKeyChecking=no" wordpress/wp-content/plugins/ ubuntu@52.205.227.18:/home/ubuntu/wp/disk/wordpress/wp-content/plugins/
        echo "rsync live done"
        echo "rsync stage"
        rsync -r --timeout=300 -e "ssh -i keyfile -o StrictHostKeyChecking=no" wordpress/wp-content/themes/ ubuntu@52.205.227.18:/home/ubuntu/wp/disk/wordpress_staging/wp-content/themes/
        rsync -r --timeout=300 -e "ssh -i keyfile -o StrictHostKeyChecking=no" wordpress/wp-content/plugins/ ubuntu@52.205.227.18:/home/ubuntu/wp/disk/wordpress_staging/wp-content/plugins/
        echo "rsync stage done"



