name: Stage
on:
  push:
    branches: ["workflows"]

jobs:
  ssh-into:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Copying files to the destination
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        LIVE_USER: ubuntu
        HOST: 52.205.227.18
        PORT: 22
        DEST: /home/ubuntu/deployment
      run: |
        echo -e "${SSH_KEY}" > keyfile
        chmod 600 keyfile
        rsync -r --timeout=300 -e "ssh -i keyfile -o StrictHostKeyChecking=no" wordpress/wp-content/themes/astra-child/* ubuntu@52.205.227.18:/home/ubuntu/deployment
        



