name: Stage
on:
  push:
    branches: ["workflows"]

jobs:
  ssh-into:
    runs-on: ubuntu-latest

    steps:
    
      - name: Copying files to the destination
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          LIVE_USER: ubuntu
          HOST: 52.205.227.18
          PORT: 22
          DEST: /home/ubuntu/deployment
        run: |
          echo -e "${SSH_KEY}" >keyfile
          chmod 600 keyfile
          pwd
          ls
          rsync -r -e "ssh -i keyfile -o StrictHostKeyChecking=no" wordpress/wp-content/themes/astra-child/* $LIVE_USER@$HOST:/home/ubuntu/deployment
          ssh -o StrictHostKeyChecking=no -P $PORT -i keyfile $LIVE_USER@$HOST " cp -R /home/ubuntu/deployment/* /var/www/wordpress/wp-content/themes/"
          ssh -o StrictHostKeyChecking=no -P $PORT -i keyfile $LIVE_USER@$HOST " cp -R /home/ubuntu/deployment/* /var/www/wordpress/wp-content/plugins/"