name: Stage
on:
  push:
    branches: ["workflows"]

jobs:
  ssh-into:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
      name: Copying files to the destination
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        LIVE_USER: ubuntu
        HOST: 52.205.227.18
        PORT: 22
        DEST: /home/ubuntu/deployment
      run: |
        echo -e "${SSH_KEY}" > keyfile
        chmod 600 keyfile
#        ssh -o StrictHostKeyChecking=no -p $PORT -i keyfile $LIVE_USER@$HOST "cd $DEST && touch testfile1.txt"
        ssh -o StrictHostKeyChecking=no -P $PORT -i keyfile $LIVE_USER@$HOST "cd $DEST && cp -r testfile1.txt /var/www/wordpress"
